### ISSUE TITLE
切换会话后，总是显示之前的第一个问题，我觉得应该自动滚动到最新的问题

### ISSUE THREAD

**Issue by ywsmart** [37MobileTeam/iChatGPT#45]
切换会话后，总是显示之前的第一个问题，我觉得应该自动滚动到最新的问题

**Comment by iHTCboy** [comment]
@ywsmart 可以的啊，下一个版本改成滚动到底部啊

**Comment by 37MobileTech** [comment]
@ywsmart v2.7 已经调整：切换历史对话，默认滚动到最新的对话内容

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.7/iChatGPT-macOS-v2.7.zip
