### ISSUE TITLE
升级新版软件后出现以下问题

### ISSUE THREAD

**Issue by HillKubeo** [37MobileTeam/iChatGPT#54]
![WechatIMG856](https://github.com/37MobileTeam/iChatGPT/assets/127168781/eaf62bbf-7ef3-4ee5-87dd-a8b664b5355e)
请问如何解决，网页能正常登的
![WechatIMG857](https://github.com/37MobileTeam/iChatGPT/assets/127168781/72786844-26e3-4729-81df-fdb191e0bcc5)

**Comment by ywsmart** [comment]
我也遇到类似问题🙁

**Comment by iHTCboy** [comment]
@HillKubeo @ywsmart  OpenAI API Key 密钥过期了，可在 https://platform.openai.com/account/api-keys 页面查询密钥状态啊。
